---
# define SimpleInventory as our inventory management
#SimpleInventory is most important tools for inventory management

inventory:
  plugin: SimpleInventory
  options:
    host_file: "hosts.yaml"
    group_file: "groups.yaml"
    defaults_file: "defaults.yaml"


runner:
  plugin: threaded
  options:
    num_workers: 10
    