---
#moshakhas kardane inke inventory management ma chi hasrt? (maslan ansible,netbox,...)
#k mohemtarin inventory nornir SimpleInventory ast

inventory:
  plugin: SimpleInventory
  options:
    host_file: "hosts.yaml"
    group_file: "groups.yaml"
    defaults_file: "defaults.yaml"

#bakhshi ast k migim device ha chand ta chandta config shavand
runner:
  plugin: threaded
  options:
    num_workers: 10
    